name: run monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  monitor-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node src/index.js
        
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs.txt
      
      - name: Send email
        run: |
          node src/sendEmail.js
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
