name: run monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  monitor-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node monitor.js
